#!/bin/bash

echo "Installing DotFiles..."

declare -a backup 
backup=( 
    zprofile 
    scripts 
    jupyter 
    lf 
    nvim 
    shell 
    starship 
    tmux 
    zsh
)


for p in "${backup[@]}"
do
    # Deleting previous symlinks 
    stow -v -D -t ~ "$p" 
    # Stowing new symlinks
    stow -v -R -t ~ "$p"
done
