#!/bin/bash

echo "Installing Packages"
pkg install neovim tmux stow zsh lf ranger nodejs-lts starship python git tree -y &&

pip install pipenv youtube-dl &&

pip install wheel &&
pkg install libjpeg-turbo &&
LDFLAGS="-L/system/lib/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install pillow jupyter &&

# Vim Plug (neovim)
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' &&

echo "Cloning repo"
mkdir Git/ &&
cd Git &&
git clone https://github.com/hoshiya4522/dotfiles mydotfiles &&

cd dotfiles/ &&

./installdots.sh &&


echo DONE
