#!/bin/bash

echo "Installing Spark.bash"
sudo sh -c "curl https://raw.githubusercontent.com/holman/spark/master/spark -o /usr/local/bin/spark && chmod +x /usr/local/bin/spark"
sudo pacman -S lolcat


echo "Installing vim-plug for neovim"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' 


echo "Installing TPM for Tmux"
git clone https://github.com/tmux-plugins/tpm ~/.config/plugins/tmux/tpm 


echo "Installing Zsh Plugins" &&
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/plugins/zsh/zsh-autosuggestions 
git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.config/plugins/zsh/zsh-syntax-highlighting
git clone https://github.com/joshskidmore/zsh-fzf-history-search ~/.config/plugins/zsh/zsh-fzf-history-search

if [ -d ~/.local ]; then
    if [ -d ~/.local/bin ]; then
        curl -q https://raw.githubusercontent.com/JopStro/bspswallow/master/bspswallow >> ~/.local/bin/bspswallow
        chmod +x ~/.local/bin/bspswallow
    else
        mkdir ~/.local/bin
    fi
else
    mkdir ~/.local
fi

