#!/bin/bash

# export $DOTFILES in your shell profile
pushd ~/.dotfiles/configs


echo "Installing DotFiles..."

# Deleting previous symlinks 
stow -v -D -t ~ *

# Stowing new symlinks
stow -v -R -t ~ *
