# vim:fileencoding=utf-8:foldmethod=marker

include current-theme.conf
shell /usr/bin/zsh

background_opacity 0.8
background_blur 1

font_size        15
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

placement_strategy center
window_padding_width 10

confirm_os_window_close 0

selection_foreground none
selection_background none
selection_style reverse
