#!/bin/bash

alias ls="eza --icons -F --group-directories-first"
alias tree="eza --tree --icons -F --group-directories-first"
alias ll="ls -lh"
alias lla="ls -lAh"
alias la="ls -A"
alias sl=ls # because im retarded
alias rm=trash
alias pac="sudo pacman"

alias here="dolphin . & disown"

# Chezmoi specific
alias chez="chezmoi"
alias cz="chezmoi"
alias czc="cd /home/hoshiya4522/.local/share/chezmoi"
alias czl="czc && lazygit && cd -"

alias wget="wget -c"

source /home/hoshiya4522/.config/self/.scripts/aliases


# rewrite nvim
# Define an alias pointing to your custom Neovim config directory
alias renvim="NVIM_APPNAME=renvim nvim"

