#!/bin/bash

alias ls="eza --icons --group-directories-first"
alias rm=trash
alias pac="sudo pacman --needed"
alias chezcd="cd /home/hoshiya4522/.local/share/chezmoi"


source /home/hoshiya4522/.config/self/.scripts/aliases
