# -*- conf -*-

shell=/usr/bin/zsh

include=/usr/share/foot/themes/tokyonight-night
include=/home/hoshiya4522/.config/foot/vague.ini
# include=/usr/share/foot/themes/nord
# include=/usr/share/foot/themes/gruvbox
# include=/usr/share/foot/themes/gruvbox-dark
# include=/usr/share/foot/themes/tokyonight-storm

font=JetBrainsMono Nerd Font Propo:size=14
font-bold=JetBrainsMono Nerd Font Propo:size=14:style=bold
font-italic=JetBrainsMono Nerd Font Propo:size=14:style=italic
font-bold-italic=JetBrainsMono Nerd Font Propo:size=14:style=bold:italic

pad=10x10

[mouse]
hide-when-typing=yes
# alternate-scroll-mode=yes

[colors-dark]
alpha=0.8
blur=yes

[colors-light]
alpha=0.8
blur=yes

[csd]
border-width=2
border-color=FFFFFF

[key-bindings]
quit=Control+q
search-start=Control+Shift+f
show-urls-launch=Control+Shift+o

# vim: ft=dosini
